### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by peterennis** [danielsvane/lettersdb#1]
C:\ae\lettersdb>meteor
[[[[[ C:\ae\lettersdb ]]]]]

=> Started proxy.
=> Meteor 0.8.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

While building the application:
error: no such package: 'mongodb-aggregation'
error: no such package: 'bootstrap-3'
error: no such package: 'GAnalytics'

I followed the meteorite install for windows from here:
http://www.danielsvane.dk/blog/meteor-and-meteorite-on-windows
and use it to update

C:\ae\lettersdb>meteorite install mongodb-aggregation
√ mongodb-aggregation
    tag: https://github.com/jhoxray/meteor-mongo-extensions.git#v0.1.71

fs.js:735
  return binding.symlink(preprocessSymlinkDestination(destination, type),
                 ^
Error: EPERM, operation not permitted 'C:\Users\peterennis\AppData\Local.meteor
ite\packages\mongodb-aggregation\jhoxray\meteor-mongo-extensions\da9661c47b3797c
ec062005f01f84a4723051438'
    at Object.fs.symlinkSync (fs.js:735:18)
    at C:\Users\peterennis\AppData\Roaming\npm\node_modules\meteorite\lib\depend
encies\package.js:131:10
    at C:\Users\peterennis\AppData\Roaming\npm\node_modules\meteorite\lib\source
s\git.js:84:15

etc.

**Comment by peterennis** [comment]
Update meteor and try again:

C:\ae\lettersdb>meteor --version
Release 0.8.2

C:\ae\lettersdb>meteor update
lettersdb: updated to Meteor 0.8.3.

C:\ae\lettersdb>meteorite install mongodb-aggregation

fs.js:735
  return binding.symlink(preprocessSymlinkDestination(destination, type),
                 ^
Error: EPERM, operation not permitted 'C:\Users\peterennis\AppData\Local.meteor
ite\packages\mongodb-aggregation\jhoxray\meteor-mongo-extensions\da9661c47b3797c
ec062005f01f84a4723051438'
    at Object.fs.symlinkSync (fs.js:735:18)
    at C:\Users\peterennis\AppData\Roaming\npm\node_modules\meteorite\lib\depend
encies\package.js:131:10

**Comment by peterennis** [comment]
old
